# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /mnt/SSD870/UnrealEngine/Linux_Unreal_Engine_5.5.0_preview-1

TARGETS = \
	DoomsDayge-Android-DebugGame  \
	DoomsDayge-Android-Development  \
	DoomsDayge-Android-Shipping  \
	DoomsDayge-Linux-DebugGame  \
	DoomsDayge-Linux-Development  \
	DoomsDayge-Linux-Shipping  \
	DoomsDayge-LinuxArm64-DebugGame  \
	DoomsDayge-LinuxArm64-Development  \
	DoomsDayge-LinuxArm64-Shipping  \
	DoomsDayge \
	DoomsDaygeEditor-Linux-DebugGame  \
	DoomsDaygeEditor-Linux-Development  \
	DoomsDaygeEditor \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend DoomsDaygeEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug DoomsDaygeEditor-Linux-Debug


DoomsDayge-Android-DebugGame:
	 $(BUILD) DoomsDayge Android DebugGame  -Project="/home/madmonki/EVO870/unrealprojs/EscapeRoomProj/EscapeRoomProj.uproject" $(ARGS)

DoomsDayge-Android-Development:
	 $(BUILD) DoomsDayge Android Development  -Project="/home/madmonki/EVO870/unrealprojs/EscapeRoomProj/EscapeRoomProj.uproject" $(ARGS)

DoomsDayge-Android-Shipping:
	 $(BUILD) DoomsDayge Android Shipping  -Project="/home/madmonki/EVO870/unrealprojs/EscapeRoomProj/EscapeRoomProj.uproject" $(ARGS)

DoomsDayge-Linux-DebugGame:
	 $(BUILD) DoomsDayge Linux DebugGame  -Project="/home/madmonki/EVO870/unrealprojs/EscapeRoomProj/EscapeRoomProj.uproject" $(ARGS)

DoomsDayge-Linux-Development:
	 $(BUILD) DoomsDayge Linux Development  -Project="/home/madmonki/EVO870/unrealprojs/EscapeRoomProj/EscapeRoomProj.uproject" $(ARGS)

DoomsDayge-Linux-Shipping:
	 $(BUILD) DoomsDayge Linux Shipping  -Project="/home/madmonki/EVO870/unrealprojs/EscapeRoomProj/EscapeRoomProj.uproject" $(ARGS)

DoomsDayge-LinuxArm64-DebugGame:
	 $(BUILD) DoomsDayge LinuxArm64 DebugGame  -Project="/home/madmonki/EVO870/unrealprojs/EscapeRoomProj/EscapeRoomProj.uproject" $(ARGS)

DoomsDayge-LinuxArm64-Development:
	 $(BUILD) DoomsDayge LinuxArm64 Development  -Project="/home/madmonki/EVO870/unrealprojs/EscapeRoomProj/EscapeRoomProj.uproject" $(ARGS)

DoomsDayge-LinuxArm64-Shipping:
	 $(BUILD) DoomsDayge LinuxArm64 Shipping  -Project="/home/madmonki/EVO870/unrealprojs/EscapeRoomProj/EscapeRoomProj.uproject" $(ARGS)

DoomsDayge: DoomsDayge-Linux-Development

DoomsDaygeEditor-Linux-DebugGame:
	 $(BUILD) DoomsDaygeEditor Linux DebugGame  -Project="/home/madmonki/EVO870/unrealprojs/EscapeRoomProj/EscapeRoomProj.uproject" $(ARGS)

DoomsDaygeEditor-Linux-Development:
	 $(BUILD) DoomsDaygeEditor Linux Development  -Project="/home/madmonki/EVO870/unrealprojs/EscapeRoomProj/EscapeRoomProj.uproject" $(ARGS)

DoomsDaygeEditor: DoomsDaygeEditor-Linux-Development

LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/home/madmonki/EVO870/unrealprojs/EscapeRoomProj/EscapeRoomProj.uproject" -Game 

.PHONY: $(TARGETS)
